<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>WPF-UI.Tray</PackageId>
    <TargetFrameworks>net10.0-windows;net9.0-windows;net8.0-windows;net481;net472;net462</TargetFrameworks>
    <Description>Native tray menu icon support for WPF using the WPF UI library.</Description>
    <CommonTags>$(CommonTags);tray;notifyicon;notify</CommonTags>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <!-- for development -->
    <PlatformTarget>x64</PlatformTarget>

    <BuildAllPlatformsForPackage Condition="'$(BuildAllPlatformsForPackage)' == ''">false</BuildAllPlatformsForPackage>

    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddPlatformPackageFiles</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildAllPlatformsForPackage)' == 'true'">
    <!-- for NuGet packing -->
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <IncludeBuildOutput>false</IncludeBuildOutput> <!-- skip regular build output; we need subdirs -->
  </PropertyGroup>

  <ItemGroup>
    <None Include="VisualStudioToolsManifest.xml" Pack="true" PackagePath="tools" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controls\NotifyIcon.bmp" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Controls\NotifyIcon.bmp" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net462'">
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <PackageReference Include="System.ValueTuple" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wpf.Ui\Wpf.Ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="WpfAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackagePlatform Include="x86" Rid="win-x86" PlatformTarget="x86"/>
    <PackagePlatform Include="x64" Rid="win-x64" PlatformTarget="x64"/>
    <PackagePlatform Include="ARM64" Rid="win-arm64" PlatformTarget="ARM64"/>
  </ItemGroup>

  <Target Name="BuildAllPlatforms"
          Condition="'$(IsPackingPlatformBuild)' != 'true'">
    <MSBuild Projects="$(MSBuildProjectFullPath)"
             Targets="Build"
             Properties="Configuration=$(Configuration);
                       Platform=%(PackagePlatform.Identity);
                       PlatformTarget=%(PackagePlatform.PlatformTarget);
                       RuntimeIdentifier=%(PackagePlatform.Rid);
                       IsPackingPlatformBuild=true" />
  </Target>

  <Target Name="AddPlatformPackageFiles"
          DependsOnTargets="BuildAllPlatforms"
          Condition="'$(IsPackingPlatformBuild)' != 'true'">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(MSBuildProjectDirectory)\bin\%(PackagePlatform.Identity)\$(Configuration)\$(TargetFramework)\%(PackagePlatform.Rid)\$(AssemblyName).dll"
            Pack="true"
            PackagePath="runtimes\%(PackagePlatform.Rid)\lib\$(TargetFramework)\" />

      <!-- serves as a reference assembly -->
      <TfmSpecificPackageFile Include="$(MSBuildProjectDirectory)\bin\x64\$(Configuration)\$(TargetFramework)\win-x64\$(AssemblyName).dll"
            Pack="true"
            PackagePath="lib\$(TargetFramework)\" />
    </ItemGroup>
  </Target>

</Project>
