name: DotNet Main

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            buildprops:
              - 'Directory.Build.props'

      - name: Publish
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/WPFUI/WPFUI.csproj
          VERSION_FILE_PATH: src/Directory.Build.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false
